### ISSUE TITLE
Remove "reserved" from the Admin and kibanaserver passwords 

### ISSUE THREAD

**Issue by Jon-AtAWS** [opendistro/for-elasticsearch-docs#12]
Since these passwords ship with default values, we need to make it easy to set them. Especially running Docker, it's hard to change them and that reduces the security footprint.

Removing the reserved designation will allow us to change them in the Security UI.

**Comment by aetter** [comment]
Hi @Jon-AtAWS, I'm going to close this out and continue the discussion in https://github.com/opendistro-for-elasticsearch/security/issues/10

I think we need to give the removal of `readonly` from those accounts some thought; there's some definite appeal to forcing people to have SSH access to the box in order to change the admin password. If you remove the read-only designation, you can change them using the REST API, which opens the cluster up to a much larger surface area.
