### ISSUE TITLE
customerror?type=authError (Openid + Kibana)

### ISSUE THREAD

**Issue by kssrivathsa** [opendistro/for-elasticsearch-docs#227]
Keycloak redirects to below url after authentication. 
http://odfe-kibana:5601/customerror?type=authError.

Here is my kibana.yml
***
server.name: odfe-kibana
server.host: "0"
opendistro_security.auth.type: "openid"

opendistro_security.openid.connect_url: "http://openid.server:8080/auth/realms/myrealm/.well-known/openid-configuration"

opendistro_security.openid.client_id: "kibanasso"

opendistro_security.openid.client_secret: "secretpassword"
opendistro_security.openid.base_redirect_url: "http://odfe-kibana:5601"
opendistro_security.openid.header: "Authorization"

elasticsearch.hosts: https://odfe-node1:9200

elasticsearch.ssl.verificationMode: none
elasticsearch.username: kibanaserver
elasticsearch.password: kibanaserver
elasticsearch.requestHeadersWhitelist: ["securitytenant","Authorization"]
opendistro_security.cookie.secure: false

opendistro_security.multitenancy.enabled: true
opendistro_security.multitenancy.tenants.preferred: ["Private", "Global"]
opendistro_security.readonly_mode.roles: ["kibana_read_only"]

newsfeed.enabled: false
telemetry.optIn: false
telemetry.enabled: false
***
Not sure what is going wrong.

**Comment by aetter** [comment]
Hi @kssrivathsa, we often can't help with configuration issues with third-party integrations due to our inability to troubleshoot on the OpenID/SAML/LDAP/proxy side. Nothing looks obviously wrong. My only suggestions are to make sure you've also done the [Elasticsearch configuration](https://opendistro.github.io/for-elasticsearch-docs/docs/security-configuration/openid-connect/#elasticsearch-configuration) and restarted your nodes. Beyond that, check out [the forums](https://discuss.opendistrocommunity.dev/).
