### ISSUE TITLE
Add statement about ODFE backward compatibility

### ISSUE THREAD

**Issue by ylwu-amzn** [opendistro/for-elasticsearch-docs#237]
Don't think ODFE supports backward compatibility very well. And we don't have test cases for this.  But we don't state this on ODFE upgrade document: https://opendistro.github.io/for-elasticsearch-docs/docs/upgrade/rolling/

Some user may follow this doc to upgrade ODFE domain to new version which is risky. We have already received [one issue about anomaly detection plugin can't work after upgrading](https://github.com/opendistro-for-elasticsearch/anomaly-detection-kibana-plugin/issues/167).

**Comment by aetter** [comment]
Is this a confirmed bug in AD? Do other plugins have the same issue? One of the assurances with semantic versioning is that things shouldn't break between minor versions. If we're not willing to hold up that end of the contract, we need to preface every upgrade with disclaimers and generally impact the credibility of our offering. The solution here is for our plugins to work the way that any informed user would expect: 1.x -> 1.y is fine, 1.x -> 2.x might have breakages.

**Comment by ylwu-amzn** [comment]
> our plugins to work the way that any informed user would expect: 1.x -> 1.y is fine, 1.x -> 2.x might have breakages.

Do we have backward compatibility test case for this? Don't think we do such backward compatibility when release new version.

**Comment by aetter** [comment]
Maybe I'm not understanding the issue, but some simple statements here:

- Lack of BC between minor versions is a bug.
- If we don't have BC test cases, we should add them.
- If you look at the AWS ES upgrade doc, you'll note that the 5.x to 5.6 and 6.x to 6.x rows have no notes next to them, because minor version upgrades should just work.  If they don't, that's a bug.

If it's only rolling upgrades that are impacted, great, I can pull that page and tell people to do a cluster restart upgrade, but this is enterprise software. There has to be an upgrade path, and it has to work between minor versions.

**Comment by aetter** [comment]
https://opendistro.github.io/for-elasticsearch-docs/docs/upgrade/1-8-0/
