### ISSUE TITLE
Issue connecting Tableau to Elasticsearch

### ISSUE THREAD

**Issue by prwoble** [opendistro/for-elasticsearch-docs#256]
We are trying to connect Tableau to Elasticsearch. In order to do so, we had to set up a System DSN by following the steps on this site:
https://opendistro.github.io/for-elasticsearch-docs/docs/sql/odbc/
We had to configure the DSN using the ODBC administrator as well as copying the odfe_sql_odbc.tde file to the Documents\My Tableau Repository\Datasources folder:
![image](https://user-images.githubusercontent.com/67025085/84828478-1eb0b680-aff4-11ea-863d-6bf6ba8ac3b5.png)

In Tableau, we are using the odbc connector to connect to the DSN we just built. So we opened Tableau and followed these steps:
Connect to a server > More... > Other Databases (ODBC) > DSN

We then selected the System DSN we just created to connect to our Elasticsearch server and hit connect. The connection attributes automatically populated and we then hit sign in.
![image](https://user-images.githubusercontent.com/67025085/84827950-42bfc800-aff3-11ea-87fc-b7ba1338bfb1.png)

It signed us in as we had hoped, but when we went to hit 'Select Database' and chose the database that was shown, we received an error message saying 'The protocol is disconnected'. This is the what displays the error:
![image](https://user-images.githubusercontent.com/67025085/84828016-5a974c00-aff3-11ea-89a2-e3192a40d961.png)

We are using opendistro for elasticsearch version 1.8.0 and the ODBC Driver for elasticsearch version 7.07.01.00.

**Comment by jordanw-bq** [comment]
Hi @prwoble,

The Open Distro for Elasticsearch server requires that you use the Open Distro for Elasticsearch ODBC Driver for connecting to it: https://github.com/opendistro-for-elasticsearch/sql-odbc

A 1.8.0.0 version of the ODFE ODBC Driver (with initial pagination support) is available [here](https://github.com/opendistro-for-elasticsearch/sql-odbc/issues/94) (you will want the `windows64-installer`).

A Tableau Connector (TaCo) is currently in development, and will help improve the connection experience using Tableau. You can try this instead of the TDC
https://github.com/opendistro-for-elasticsearch/sql-odbc/tree/master/src/TableauConnector/odfe_sql_odbc

Please feel free to raise any ODBC driver or TaCo-related issues on the `opendistro-for-elasticsearch/sql-odbc` repository.
