### ISSUE TITLE
add  roles, roles_mapping ,indices on kibana can't synchronize to configuration file of opendistro_security

### ISSUE THREAD

**Issue by HLLavender** [opendistro/for-elasticsearch-docs#26]
I found that these new configurations could not be synchronized to the relevant configuration files on  opendistro_security,When I add a roles,role_mapping,internal user to the kibana page.and when 
i upload the changes via sgadmin  ,configuration files is gone on kibana page . I wonder why settings isn't synchronous.

**Comment by HLLavender** [comment]
install of rpm

**Comment by aetter** [comment]
Hi @HLLavender, if I'm understanding correctly, this is intentional. The configuration files only store initial configuration. Most configuration is stored in the `.opendistro_security` index in the cluster itself so that it can be shared between nodes. You can [dump the index](https://opendistro.github.io/for-elasticsearch-docs/docs/security/security-admin/#backup-and-restore) to a set of configuration files if you want to migrate them to a new cluster.
