### ISSUE TITLE
how to switch from opensource-ELK to open-distro without losing any of my existing data

### ISSUE THREAD

**Issue by arnabdutta** [opendistro/for-elasticsearch-docs#27]
I have an existing ELK set-up running, which has been collecting/storing data for some time. How do I switch to open-distro ES from my existing set-up without losing all the data. Any documentation regarding that will be really helpful.

**Comment by aetter** [comment]
Hi @arnabdutta, thanks for the issue. When moving from one service or stack to another, you'd typically use a snapshot to perform the migration.

We currently have no documentation on snapshot and restore, but it's in my backlog. If anyone wants to tackle it, I think `docs/elasticsearch/snapshot-restore.md` would be the appropriate place.

Because this is the shorter thread, I'm going to close https://github.com/opendistro/for-elasticsearch-docs/issues/7 as a duplicate and leave this one open.

**Comment by pbuxtonccuk** [comment]
How about using elasticdump??  

The steps here worked for me on an admittedly small test.

https://devopstar.com/2019/03/13/open-distro-for-elasticsearch-kickstart-guide/

**Comment by aetter** [comment]
https://github.com/opendistro/for-elasticsearch-docs/pull/42
