### ISSUE TITLE
Unable to disable authentication for kibana

### ISSUE THREAD

**Issue by reneleite** [opendistro/for-elasticsearch-docs#32]
I would like to turn off authentication for kibana/elasticsearch in order to evaluate the benefits of the SQL and Alerting in the Open Distro. I was able to do it for elasticsearch using opendistro_security.disabled: true in the elasticsearch.yml file. How can I do the same for kibana.yml ?

I do not need login/password for now as the resources are in an isolated environment/not in production

**Comment by aetter** [comment]
Hi @reneleite, if you're using the RPM installation, it's semi-straightforward. You'll need to remove all the `opendistro_security` lines from `kibana/config/kibana.yml`, change `elasticsearch.url` to `http` rather than `https`, delete `kibana/plugins/opendistro_security`, and restart Kibana.

If you're using the Docker image, it's more complicated. The best way, I think, is to [build your own `Dockerfile`](https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/#run-with-custom-plugins) using the Kibana image and run `/usr/share/kibana/bin remove opendistro_security`. Then build with your own tag and run that instead of the original image.

You can override `kibana.yml` in `docker-compose.yml` or when you build your image. I'll do some more testing and get steps into the documentation.

**Comment by aetter** [comment]
Added information here: https://opendistro.github.io/for-elasticsearch-docs/docs/security/disable/
