### ISSUE TITLE
Dark mode for documentation

### ISSUE THREAD

**Issue by SebastianThorn** [opendistro/for-elasticsearch-docs#383]
Hi, I was wondering if is would be possible to add a toogle on the top of the doc-pages to get a darker mode.
Something like they have for docker, https://docs.docker.com/

Br Sebastian

**Comment by aetter** [comment]
Hi @SebastianThorn, it's definitely possible. We'd need to cook up a new [color scheme](https://github.com/opendistro/for-elasticsearch-docs/tree/master/_sass/color_schemes) that worked well with the ODFE brand colors and then add a little JS toggle like Docker or [our base theme](https://pmarsceill.github.io/just-the-docs/docs/customization/#color-schemes) have.

It's unlikely we'll prioritize the work, but I'll leave this issue open because a) it's a great idea and b) maybe someone from the community will take a stab at it.

**Comment by SebastianThorn** [comment]
Cool, I understand this wont be a proprity. :)

**Comment by aetter** [comment]
Closing in favor of https://github.com/opensearch-project/documentation-website/issues/15
