### ISSUE TITLE
Add search examples to new rollup pages

### ISSUE THREAD

**Issue by neographikal** [opendistro/for-elasticsearch-docs#384]
https://opendistro.github.io/for-elasticsearch-docs/docs/ism/index-rollups/

It is unclear to me how the data in the rollup index is structured and how I can get data out of it. Just querying _search with a match all does not work, size has to 0. Also in Kibana you can't view the data in the rollup index it seems.

**Comment by dbbaughe** [comment]
Hi @neographikal, the data is not available for returning the hits as its stored in a different internal structure which is why we require size to be 0; we do not want any users to take a dependency on the structure of the internal data as we want to reserve the ability to change it as needed. Rollups are used for answering aggregations. So you can continue to use the _search endpoint, use the query part for filtering the subset of documents, and the aggregation returning the results you want.

**Comment by neographikal** [comment]
Yes, but since I can't view the contents of the index it is difficult to know how to query the index. Some simple examples would help a lot :)

**Comment by dbbaughe** [comment]
Hey @neographikal,

You query it the same way you query the source index that was rolled up. It's written in a way that we intercept the queries and rewrite them to the internal format of the target index. Based on how you configured your rollup job should determine what type of queries the target index will support. We will definitely work on adding some examples to the documentation.

**Comment by neographikal** [comment]
Thanks, will try as soon as the new update is out (continuous rollup bug fixed).

**Comment by dbbaughe** [comment]
@neographikal 
Just in case you want to use before new ODFE release, you can look at the last comment on this issue:
https://github.com/opendistro-for-elasticsearch/index-management/issues/374

It has a link to the artifacts generated with the fixes for continuous rollups.

**Comment by neographikal** [comment]
I know, thanks! It would help to add documentation, even your quote in this issue would help, examples would be even better. Will look into it soon!

**Comment by ashwinkumar12345** [comment]
@neographikal - Added rollup example to the docs - https://github.com/opendistro/for-elasticsearch-docs/pull/391/files.

**Comment by neographikal** [comment]
Thanks!!
