### ISSUE TITLE
Documentation for Alerting Get Alerts API

### ISSUE THREAD

**Issue by qreshi** [opendistro/for-elasticsearch-docs#417]
For ODFE 1.10+ a `Get Alerts` API [was added](https://github.com/opendistro-for-elasticsearch/alerting/blob/main/alerting/src/main/kotlin/com/amazon/opendistroforelasticsearch/alerting/resthandler/RestGetAlertsAction.kt) to the Alerting plugin. 

Creating this issue to track adding this to the [Alerting API](https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/api/) section. Also the description for [Acknowledge Alert](https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/api/#acknowledge-alert) should be updated to recommend using the `Get Alerts` API.

Also, out of curiosity, does the documentation support viewing versions for different corresponding ODFE versions? And if not, should it? It looks like some API or behavior changes across versions but the there is only one documentation version and it confuses users.

**Comment by aetter** [comment]
Hi @qreshi, thanks for the heads-up. If you feel like trying your hand at a PR, it's all Markdown. Otherwise, I suspect @keithhc2 can handle it over the next few weeks.

For the second question, we currently host a [few selected older releases](https://opendistro.github.io/for-elasticsearch-docs/docs/other/#old-documentation-versions) and have plans to [host more in the future](https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/621).

Older versions present a problem, though, in that we do *not* backport bug fixes or content additions, so even if you're on 1.12, the 1.14 documentation might be more useful, accurate, comprehensive, etc. I'm 50/50 on whether we'll ever put a version switcher into the lower-left or if we'll keep them tucked away on an Old Versions page.

**Comment by qreshi** [comment]
Yeah, I agree that having the older versions has it's own problems but similar to the Alerting scenario mentioned above, there are sometimes API additions or changes that are accurate for the current newest version but possibly doesn't apply to the older version of ODFE and then the user gets confused why the API call isn't working (since it's not supported on their version). Having some way to communicate those kinds of discrepancies more effectively might be helpful and establishing that process should ensure that the plugin owners are relaying that information so it's captured somewhere.

**Comment by keithhc2** [comment]
Closed as #468
