### ISSUE TITLE
Is it possible to connect opendistro for elasticsearch kibana to AWS elasticsearch service

### ISSUE THREAD

**Issue by sphansekar-cci** [opendistro/for-elasticsearch-docs#46]
I am using AWS elasticsearch service, I want to use opendistro for elasticsearch kibana and point to AWS elasticsearch service.
Please let me know what steps I need to take.

**Comment by sphansekar-cci** [comment]
#7

**Comment by aetter** [comment]
Hi @sphansekar-cci, so because Amazon Elasticsearch Service doesn't use the Security plugin, you're probably better off using Kibana on the service `<your-domain>/_plugins/kibana` (which includes Alerting) or a vanilla version of Kibana that doesn't include the Open Distro for Elasticsearch plugins.

If you install Open Distro for Elasticsearch and then want to connect it to Amazon ES, you need to [remove the Security plugin from Kibana](https://opendistro.github.io/for-elasticsearch-docs/docs/security/disable/#remove-kibana-plugin) and then follow the steps here: https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-kibana.html#es-kibana-local

All the usual network connectivity/security considerations apply: Kibana has to be able to reach the cluster and not get denied when its requests arrive.
