### ISSUE TITLE
change admin password

### ISSUE THREAD

**Issue by bollicino** [opendistro/for-elasticsearch-docs#5]
Hi, is it possible to change the default admin password?

**Comment by aetter** [comment]
Hi @bollicino, the intent is that you would create your own users or hook up an authentication provider rather than modifying the demo users, but the short answer is "yes, you can." I'll try to find a decent spot for this content in the documentation, but it's pretty complicated.

This is on the RPM distribution. For Docker, you would have to overwrite files before running the image.

Basically, you run the hash tool to generate a new password hash:

```bash
cd /usr/share/elasticsearch/plugins/opendistro_security/tools
sudo sh hash.sh -p cleartext
$2y$12$C/543Qr4Y7Zy4Wsq5WvN9uw.WAbpvGghpiXvk9WexZgDfAGuG0OEC
```

Then copy and paste the hashed password into `internal_users.yml` in the `hash` field:

```bash
sudo vi /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml
```

Finally, to apply the change, run:

```bash
sudo sh securityadmin.sh -cd ../securityconfig/ -icl -nhnv -cacert /etc/elasticsearch/root-ca.pem -cert /etc/elasticsearch/kirk.pem -key /etc/elasticsearch/kirk-key.pem
```

This command uses the demo certificates, but replace the names/paths with your own certificates as necessary. Then to check that the password applied successfully, run:

```bash
$ curl -XGET -k https://localhost:9200 -u admin:admin
Unauthorized

$ curl -XGET -k https://localhost:9200 -u admin:cleartext
{
  "name" : "0yAIeJY",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "isaCyPzNR6yy-n8epKSc8w",
  "version" : {
    "number" : "6.5.4",
    "build_flavor" : "oss",
    "build_type" : "rpm",
    "build_hash" : "d2ef93d",
    "build_date" : "2018-12-17T21:17:40.758843Z",
    "build_snapshot" : false,
    "lucene_version" : "7.5.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

For most users, you can just use the Kibana UI, but for `readonly` users like `admin`, I think this is the only path. I'll leave this issue open until I've at least partially addressed the concern in the docs. Let me know if it works out for you!

**Comment by aetter** [comment]
Closing out now that https://github.com/opendistro/for-elasticsearch-docs/pull/15 is merged.

**Comment by DILIPCHIRU** [comment]
Hi ,

How can i change for a different hostname and the IP Please tell me

**Comment by mvsn98** [comment]
Whenever I use that hash.sh file to generate hash value for a string, I observe that A DIFFERENT HASH VALUE IS GENERATED EVERYTIME FOR THE SAME STRING ONLY. And this is why when I tried to change admin's password using this method, I could no longer log into the kibana system.

Please tell me how to fix hash.sh file so that it generates same hash value for the password I enter, every time....

**Comment by dminovski0** [comment]
> Hi @bollicino, the intent is that you would create your own users or hook up an authentication provider rather than modifying the demo users, but the short answer is "yes, you can." I'll try to find a decent spot for this content in the documentation, but it's pretty complicated.

@aetter Thanks, the commands worked but I used bash instead of sh with Ubuntu 18.04.
