### ISSUE TITLE
Update Debian Installation docs 

### ISSUE THREAD

**Issue by rlk5546** [opendistro/for-elasticsearch-docs#62]
Update Docs for Deb INSTALL Guide.  OpenJDK11 and apt-transport-https

1.  OpenJDK11 Ubuntu and Debian installation is not the same.  Suggest the following minor change, (in bold):

"Install Java 11:

- **Ubuntu:**   sudo add-apt-repository ppa:openjdk-r/ppa
- **Debian:    `sudo echo 'deb http://deb.debian.org/debian stretch-backports main' > /etc/apt/sources.list.d/backports.list`**

2.  Before "4   Install OpenDistro for ElasticSearch:" the following needs to be added or indicated earlier as a pre-requisite.

- **apt install apt-transport-https**

The previous `sudo apt update` will fail without apt-transport-https

These are the only two issues found while following the instructions from a clean, headless  debian 9.8 installation.

**Comment by aetter** [comment]
Hi @rlk5546, I really appreciate the testing and detailed issue. I'd prefer not to add the content inline, because it's not one of the operating systems we use for testing and makes the instructions harder to follow, but I've added your tips to the bottom of the page and am happy to add additional sections for any other Debian-based distributions that people test. Thanks!

https://github.com/opendistro/for-elasticsearch-docs/commit/554f6e1c8874308e8991219e9889ec96b32c3a6b
