### ISSUE TITLE
Unable to query multiple indexes by pattern if the index patterns differ

### ISSUE THREAD

**Issue by ion-storm** [opendistro/for-elasticsearch-docs#69]
Since Elasticsearch uses many databases users will likely have a need to query more than 1 index at a time.  It appears that this is currently impossible if indexes have different mappings.  Would these commits resolve this issue?

https://github.com/elastic/elasticsearch/commit/2274c3c80ee328ba0cde6b8bbf8771d35c443817

**Comment by aetter** [comment]
Hi @ion-storm, yep, you currently can't query more than one index using SQL if the mappings differ. I'd encourage you to open a feature request on the SQL plugin: https://github.com/opendistro-for-elasticsearch/sql

Our implementation is different from Elastic's (and uses Apache 2.0 rather than a proprietary license), so it's not a question of cherry picking some commits.
