### ISSUE TITLE
elasticsearch: java.net.MalformedURLException: unknown protocol: jrt

### ISSUE THREAD

**Issue by anelshaer** [opendistro/for-elasticsearch-docs#8]
systemctl status elasticsearch.service
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2019-03-13 08:55:02 EDT; 19s ago
     Docs: http://www.elastic.co
 Main PID: 5715 (code=exited, status=1/FAILURE)

Mar 13 08:54:46 host1 systemd[1]: Started Elasticsearch.
Mar 13 08:54:47 host1 elasticsearch[5715]: java.security.policy: error adding Entry:
Mar 13 08:54:47 host1 elasticsearch[5715]: java.net.MalformedURLException: unknown protocol: jrt
Mar 13 08:54:47 host1 elasticsearch[5715]: java.security.policy: error adding Entry:
Mar 13 08:54:47 host1 elasticsearch[5715]: java.net.MalformedURLException: unknown protocol: jrt
Mar 13 08:55:02 host1 systemd[1]: elasticsearch.service: main process exited, code=exited, status=1/FAILURE
Mar 13 08:55:02 host1 systemd[1]: Unit elasticsearch.service entered failed state.
Mar 13 08:55:02 host1 systemd[1]: elasticsearch.service failed.

**Comment by aetter** [comment]
Hi @anelshaer, can you share more details about the commands you ran to get to this point, operating system and version, and Java version? It's definitely a Java problem, and if we can figure out what went wrong, we can get it into the troubleshooting section.

**Comment by rlkarren** [comment]
Same issue.
RPM installation, followed instructions exactly.
Java 1.8
CentOS 7.6.1810
Same error shows on first run but ES shows running.

`[root@odfe ~]# service elasticsearch status -l
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2019-03-13 11:51:22 MDT; 8s ago
     Docs: http://www.elastic.co
 Main PID: 11869 (java)
    Tasks: 14
   CGroup: /system.slice/elasticsearch.service
           └─11869 /bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX...

Mar 13 11:51:22 odfe.it.usu.edu systemd[1]: Started Elasticsearch.
Mar 13 11:51:23 odfe.it.usu.edu elasticsearch[11869]: java.security.policy: error adding Entry:
Mar 13 11:51:23 odfe.it.usu.edu elasticsearch[11869]: java.net.MalformedURLException: unknown protocol: jrt
Mar 13 11:51:23 odfe.it.usu.edu elasticsearch[11869]: java.security.policy: error adding Entry:
Mar 13 11:51:23 odfe.it.usu.edu elasticsearch[11869]: java.net.MalformedURLException: unknown protocol: jrt
`

**Comment by rlk5546** [comment]
Same issue.
RPM installation, followed instructions exactly as written.
Java 1.8
CentOS 7.6.1810

$systemctl start elasticsearch
$systemctl status elasticsearch -l

● elasticsearch.service - Elasticsearch
Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; disabled; vendor preset: disabled)
Active: active (running) since Wed 2019-03-13 11:51:22 MDT; 8s ago
Docs: http://www.elastic.co
Main PID: 11869 (java)
Tasks: 14
CGroup: /system.slice/elasticsearch.service
└─11869 /bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX...

Mar 13 11:51:22 odfe.it.usu.edu systemd[1]: Started Elasticsearch.
Mar 13 11:51:23 odfe.it.usu.edu elasticsearch[11869]: java.security.policy: error adding Entry:
Mar 13 11:51:23 odfe.it.usu.edu elasticsearch[11869]: java.net.MalformedURLException: unknown protocol: jrt
Mar 13 11:51:23 odfe.it.usu.edu elasticsearch[11869]: java.security.policy: error adding Entry:
Mar 13 11:51:23 odfe.it.usu.edu elasticsearch[11869]: java.net.MalformedURLException: unknown protocol: jrt

**Comment by aetter** [comment]
Thanks @rlk5546. I'm able to reproduce and am looking into it with engineering. Looks to only be a problem on Java 8.

**Comment by aetter** [comment]
Hi everyone, our engineers tell me that those errors are nothing to worry about. If Elasticsearch fails to start, it's likely an incorrect symlink. I've added some information here: https://github.com/opendistro/for-elasticsearch-docs/commit/b4df35ffe69eef1a74c2941bd05a43b0297ce79a

**Comment by rlk5546** [comment]
Thanks! It is refreshing to see such a quick response.

**Comment by anelshaer** [comment]
I'm Still having the same Issue. 
`ln -s /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64/lib/tools.jar /usr/share/elasticsearch/lib/`

 systemctl status elasticsearch  -l
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2019-04-03 05:41:20 EDT; 2min 23s ago
     Docs: http://www.elastic.co
 Main PID: 19812 (java)
    Tasks: 78
   Memory: 1.2G
   CGroup: /system.slice/elasticsearch.service
           └─19812 /bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+AlwaysPreTouch -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -XX:-OmitStackTraceInFastThrow -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Djava.io.tmpdir=/tmp/elasticsearch.u9DTuoT1 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/lib/elasticsearch -XX:ErrorFile=/var/log/elasticsearch/hs_err_pid%p.log -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -Xloggc:/var/log/elasticsearch/gc.log -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=32 -XX:GCLogFileSize=64m -Dclk.tck=100 -Djdk.attach.allowAttachSelf=true -Djava.security.policy=file:///usr/share/elasticsearch/plugins/opendistro_performance_analyzer/pa_config/es_security.policy -Des.path.home=/usr/share/elasticsearch -Des.path.conf=/etc/elasticsearch -Des.distribution.flavor=oss -Des.distribution.type=rpm -cp /usr/share/elasticsearch/lib/* org.elasticsearch.bootstrap.Elasticsearch -p /var/run/elasticsearch/elasticsearch.pid --quiet

Apr 03 05:41:20 Test1 systemd[1]: Started Elasticsearch.
Apr 03 05:41:21 Test1 elasticsearch[19812]: java.security.policy: error adding Entry:
Apr 03 05:41:21 Test1 elasticsearch[19812]: java.net.MalformedURLException: unknown protocol: jrt
Apr 03 05:41:21 Test1 elasticsearch[19812]: java.security.policy: error adding Entry:
Apr 03 05:41:21 Test1 elasticsearch[19812]: java.net.MalformedURLException: unknown protocol: jrt

**Comment by anelshaer** [comment]
i'm still having this Issue, and when i do `systemctl status logstash`
i get the following errors:
`[WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http://localhost:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://localhost:9200/][Manticore::ClientProtocolException] localhost:9200 failed to respond"}`
